kind: Service
apiVersion: v1
metadata:
  name: focus-tracker-service
spec:
    type: NodePort
    selector:
        app: focus-tracker
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080